# Generated by Django 5.2.4 on 2026-09-01 07:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业务线名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='业务线编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '业务线',
                'verbose_name_plural': '业务线',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='环境名称')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='环境编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=64, verbose_name='显示名')),
                ('source', models.CharField(choices=[('local', '本地'), ('ldap', 'LDAP/AD')], db_index=True, default='local', max_length=16, verbose_name='认证来源')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('code', models.CharField(max_length=32, verbose_name='项目编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.business', verbose_name='所属业务线')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='操作权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='accounts.business', verbose_name='业务线')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to=settings.AUTH_USER_MODEL, verbose_name='授权用户')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='accounts.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='accounts.project', verbose_name='项目')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='accounts.role', verbose_name='授权角色')),
            ],
            options={
                'verbose_name': '数据范围',
                'verbose_name_plural': '数据范围',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='角色决定操作权限与角色级数据范围', related_name='users', to='accounts.role', verbose_name='角色'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_project_code_in_business'),
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='datascope_role_or_user_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('role', 'business', 'project', 'environment'), name='uniq_role_datascope'),
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'business', 'project', 'environment'), name='uniq_user_datascope'),
        ),
    ]
