# Generated by Django 5.2.4 on 2026-09-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='脚本名称')),
                ('code', models.CharField(help_text='业务线内唯一,如 data_sync', max_length=32, verbose_name='脚本编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('runner', models.CharField(default='python', help_text='python(默认,使用平台解释器)或解释器绝对路径;docker:xxx 二期支持', max_length=64, verbose_name='执行器/解释器')),
                ('source_type', models.CharField(choices=[('inline', '平台内代码')], default='inline', max_length=16, verbose_name='代码来源')),
                ('params_schema', models.JSONField(blank=True, default=list, help_text='参数 schema 列表,见 scripts/params.py', verbose_name='参数定义')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], db_index=True, default='disabled', max_length=16, verbose_name='状态')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='当前版本')),
                ('timeout_seconds', models.PositiveIntegerField(default=300, verbose_name='超时(秒)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='accounts.business', verbose_name='业务线')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='accounts.environment', verbose_name='环境')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_scripts', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='accounts.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('code', models.TextField(verbose_name='脚本代码')),
                ('params_schema', models.JSONField(blank=True, default=list, verbose_name='参数定义快照')),
                ('changelog', models.CharField(blank=True, max_length=255, verbose_name='变更说明')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_script_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scripts.script', verbose_name='所属脚本')),
            ],
            options={
                'verbose_name': '脚本版本',
                'verbose_name_plural': '脚本版本',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_script_code_in_business'),
        ),
        migrations.AddConstraint(
            model_name='scriptversion',
            constraint=models.UniqueConstraint(fields=('script', 'version'), name='uniq_script_version'),
        ),
    ]
