# Generated by Django 5.2.4 on 2026-09-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['id'], 'permissions': [('create_script', '可以创建脚本'), ('update_script', '可以修改脚本'), ('execute_script', '可以执行脚本')], 'verbose_name': '脚本', 'verbose_name_plural': '脚本'},
        ),
    ]
