# Generated by Django 5.2.4 on 2026-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_script_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='cpu_limit',
            field=models.FloatField(blank=True, help_text='为空不限制;Docker 用 --cpus,本地进程不应用', null=True, verbose_name='CPU 限制(核)'),
        ),
        migrations.AddField(
            model_name='script',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(blank=True, help_text='为空不限制;Docker 用 -m,本地进程用 RLIMIT_AS(POSIX)', null=True, verbose_name='内存限制(MB)'),
        ),
    ]
