# Generated by Django 5.2.4 on 2026-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_cpu_limit_script_memory_limit_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='敏感键加密存储,执行时注入 os.environ;读取不回显明文', verbose_name='环境变量'),
        ),
        migrations.AddField(
            model_name='script',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text='附加文件:[{"path": "utils/db.py", "content": "..."}],主代码在版本 code 中', verbose_name='文件集'),
        ),
        migrations.AddField(
            model_name='scriptversion',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, verbose_name='环境变量快照'),
        ),
        migrations.AddField(
            model_name='scriptversion',
            name='files',
            field=models.JSONField(blank=True, default=list, verbose_name='文件集快照'),
        ),
    ]
