# Generated by Django 5.2.4 on 2026-09-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scripts', '0002_alter_script_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='接口名称')),
                ('code', models.CharField(help_text='业务线内唯一,expose 调用路径标识', max_length=32, verbose_name='接口编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('mode', models.CharField(choices=[('expose', '暴露平台能力'), ('monitor', '监控外部接口')], max_length=16, verbose_name='模式')),
                ('method', models.CharField(default='GET', max_length=16, verbose_name='HTTP 方法')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='外部 URL')),
                ('auth_type', models.CharField(choices=[('none', '无需认证'), ('api_key', 'API Key')], default='none', max_length=16, verbose_name='认证方式')),
                ('auth_key_hash', models.CharField(blank=True, editable=False, max_length=255, verbose_name='API Key 哈希')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], db_index=True, default='disabled', max_length=16, verbose_name='状态')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='超时(秒)')),
                ('version', models.CharField(default='v1', max_length=32, verbose_name='版本')),
                ('params_schema', models.JSONField(blank=True, default=list, verbose_name='入参定义')),
                ('health_status', models.CharField(choices=[('unknown', '未知'), ('healthy', '健康'), ('degraded', '异常'), ('down', '不可用')], default='unknown', max_length=16, verbose_name='健康状态')),
                ('avg_response_ms', models.FloatField(blank=True, null=True, verbose_name='平均响应(毫秒)')),
                ('error_rate', models.FloatField(blank=True, null=True, verbose_name='错误率')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='窗口内调用次数')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='accounts.business', verbose_name='业务线')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='accounts.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='accounts.project', verbose_name='项目')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='scripts.script', verbose_name='绑定脚本')),
            ],
            options={
                'verbose_name': 'HTTP 接口',
                'verbose_name_plural': 'HTTP 接口',
                'ordering': ['id'],
                'permissions': [('view_endpoint', '可以查看接口'), ('create_endpoint', '可以创建接口'), ('update_endpoint', '可以修改接口'), ('delete_endpoint', '可以删除接口'), ('execute_endpoint', '可以调用接口')],
            },
        ),
        migrations.CreateModel(
            name='EndpointCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mode', models.CharField(choices=[('expose', '暴露平台能力'), ('monitor', '监控外部接口')], max_length=16, verbose_name='模式')),
                ('method', models.CharField(default='GET', max_length=16, verbose_name='HTTP 方法')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('response_ms', models.IntegerField(blank=True, null=True, verbose_name='响应时间(毫秒)')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='请求 ID')),
                ('caller', models.CharField(blank=True, max_length=64, verbose_name='调用方')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='endpoints.httpendpoint', verbose_name='接口')),
            ],
            options={
                'verbose_name': '接口调用记录',
                'verbose_name_plural': '接口调用记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='httpendpoint',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_endpoint_code_in_business'),
        ),
        migrations.AddIndex(
            model_name='endpointcalllog',
            index=models.Index(fields=['endpoint', '-created_at'], name='endpoints_e_endpoin_b46dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointcalllog',
            index=models.Index(fields=['success', 'created_at'], name='endpoints_e_success_f736b6_idx'),
        ),
    ]
