# Generated by Django 5.2.4 on 2026-09-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=32, verbose_name='对象 ID')),
                ('detail', models.JSONField(default=dict, verbose_name='详情')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='来源 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
