# Generated by Django 5.2.4 on 2026-09-01 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='渠道名称')),
                ('type', models.CharField(choices=[('wecom', '企业微信机器人'), ('dingtalk', '钉钉机器人'), ('email', '邮件'), ('webhook', 'Webhook')], max_length=16, verbose_name='渠道类型')),
                ('config', models.JSONField(default=dict, help_text='敏感键(webhook_url/secret/token 等)加密存储,读取时不回显明文', verbose_name='配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '告警渠道',
                'verbose_name_plural': '告警渠道',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('asset_type', models.CharField(choices=[('script', '脚本'), ('schedule', '定时任务'), ('endpoint', '接口')], max_length=16, verbose_name='监控对象类型')),
                ('asset_id', models.PositiveBigIntegerField(verbose_name='监控对象 ID')),
                ('metric', models.CharField(choices=[('consecutive_failures', '连续失败次数'), ('timeout', '执行超时'), ('endpoint_unavailable', '接口不可用'), ('endpoint_slow', '接口响应时间超限')], max_length=32, verbose_name='指标')),
                ('threshold', models.FloatField(default=1, help_text='连续失败次数 / 接口响应时间毫秒(不可用/超时规则忽略)', verbose_name='阈值')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='级别')),
                ('silent_minutes', models.PositiveIntegerField(default=30, help_text='同一规则在该窗口内不重复发送', verbose_name='静默窗口(分钟)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='accounts.business', verbose_name='业务线')),
                ('channels', models.ManyToManyField(blank=True, related_name='rules', to='alerts.alertchannel', verbose_name='告警渠道')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'ordering': ['id'],
                'permissions': [('view_alert', '可以查看告警'), ('create_alert', '可以创建告警'), ('update_alert', '可以修改告警'), ('delete_alert', '可以删除告警')],
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_type', models.CharField(max_length=16, verbose_name='对象类型')),
                ('asset_id', models.PositiveBigIntegerField(verbose_name='对象 ID')),
                ('metric', models.CharField(max_length=32, verbose_name='指标')),
                ('severity', models.CharField(max_length=16, verbose_name='级别')),
                ('message', models.TextField(verbose_name='告警内容')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('silenced', '静默抑制'), ('failed', '发送失败'), ('acked', '已确认')], db_index=True, default='sent', max_length=16, verbose_name='状态')),
                ('channels', models.JSONField(default=list, verbose_name='发送渠道')),
                ('send_result', models.JSONField(default=dict, verbose_name='发送结果')),
                ('acked_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('acked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='alerts.alertrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('asset_type', 'asset_id', 'metric', 'business'), name='uniq_alert_rule_asset_metric'),
        ),
        migrations.AddIndex(
            model_name='alertrecord',
            index=models.Index(fields=['rule', '-created_at'], name='alerts_aler_rule_id_9ca842_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecord',
            index=models.Index(fields=['status', 'created_at'], name='alerts_aler_status_f4f0a3_idx'),
        ),
    ]
