# Generated by Django 5.2.4 on 2026-09-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_type', models.CharField(choices=[('script', '脚本'), ('schedule', '定时任务'), ('endpoint', '接口')], db_index=True, max_length=16, verbose_name='资产类型')),
                ('asset_id', models.PositiveBigIntegerField(db_index=True, verbose_name='资产 ID')),
                ('trigger_type', models.CharField(choices=[('manual', '手工'), ('schedule', '定时'), ('api', '接口')], default='manual', max_length=16, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('retrying', '重试中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('canceled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('params', models.JSONField(default=dict, verbose_name='执行参数')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('request_id', models.CharField(db_index=True, max_length=36, verbose_name='请求 ID')),
                ('node', models.CharField(blank=True, max_length=64, verbose_name='执行节点')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='Worker ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.business', verbose_name='业务线')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.project', verbose_name='项目')),
                ('trigger_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_type', 'asset_id', '-created_at'], name='executions__asset_t_afeb44_idx'), models.Index(fields=['status', 'created_at'], name='executions__status_82a898_idx')],
            },
        ),
    ]
