# Generated by Django 5.2.4 on 2026-09-01 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('code', models.CharField(help_text='业务线内唯一', max_length=32, verbose_name='任务编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron 表达式'), ('interval', '周期执行')], max_length=16, verbose_name='调度方式')),
                ('cron_expr', models.CharField(blank=True, help_text='标准 5 段:分 时 日 月 周', max_length=64, verbose_name='Cron 表达式')),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='周期(秒)')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=32, verbose_name='时区')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('timeout', models.PositiveIntegerField(blank=True, help_text='为空则使用脚本超时', null=True, verbose_name='超时(秒)')),
                ('max_retries', models.PositiveIntegerField(default=0, verbose_name='最大重试次数')),
                ('retry_delay', models.PositiveIntegerField(default=60, verbose_name='重试间隔(秒)')),
                ('concurrency_limit', models.PositiveIntegerField(default=1, verbose_name='并发上限')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='执行参数')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_tasks', to='accounts.business', verbose_name='业务线')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_tasks', to='accounts.environment', verbose_name='环境')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_schedule_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_task', to='django_celery_beat.periodictask', verbose_name='调度实体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_tasks', to='accounts.project', verbose_name='项目')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_tasks', to='scripts.script', verbose_name='执行脚本')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('business', 'code'), name='uniq_schedule_code_in_business'), models.CheckConstraint(condition=models.Q(models.Q(('cron_expr__gt', ''), ('interval_seconds__isnull', True), ('schedule_type', 'cron')), models.Q(('cron_expr', ''), ('interval_seconds__isnull', False), ('schedule_type', 'interval')), _connector='OR'), name='schedule_type_fields_exclusive')],
            },
        ),
    ]
