# Generated by Django 5.2.4 on 2026-09-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletask',
            options={'ordering': ['id'], 'permissions': [('view_schedule', '可以查看定时任务'), ('create_schedule', '可以创建定时任务'), ('update_schedule', '可以修改定时任务'), ('delete_schedule', '可以删除定时任务'), ('execute_schedule', '可以执行定时任务')], 'verbose_name': '定时任务', 'verbose_name_plural': '定时任务'},
        ),
    ]
