# Generated by Django 5.2.4 on 2026-09-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='请求 ID')),
                ('task_id', models.CharField(blank=True, max_length=36, verbose_name='任务 ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='执行人')),
                ('level', models.CharField(db_index=True, default='INFO', max_length=16, verbose_name='日志级别')),
                ('node', models.CharField(blank=True, max_length=64, verbose_name='执行节点')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('extra', models.JSONField(default=dict, verbose_name='附加字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='executions.execution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['execution', 'id'], name='logs_logent_executi_ddca7d_idx'), models.Index(fields=['level', 'created_at'], name='logs_logent_level_0f4f42_idx')],
            },
        ),
    ]
