# Generated by Django 5.2.4 on 2026-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['id'], 'permissions': [('view_log', '可以查看日志')], 'verbose_name': '执行日志', 'verbose_name_plural': '执行日志'},
        ),
    ]
